################################### English language #####################################
[en]
languageName = "En"
languageCode = "en-us"
contentDir = "content"
weight = 1

[en.params]
home = "Home"
# copyright
copyright = "Copyright &copy; 2021 a hugo theme by [Themefisher](https://themefisher.com/hugo-themes/)"





