################### English navigation ####################

# main menu
[[main]]
name = "About"
url = "about/"
weight = 1

[[main]]
name = "Team"
url = "team/"
weight = 2

[[main]]
name = "Publications"
url = "publications/"
weight = 3

[[main]]
name = "Research"
url = "research/"
weight = 4

[[main]]
name = "Workshop"
url = "workshop/"
weight = 5


  
  



# footer menu

[[footer]]
name = "teacher"
url = "teacher/"

[[footer]]
name = "notice"
url = "notice/"

[[footer]]
name = "event"
url = "event/"

[[footer]]
name = "scholarship"
url = "scholarship/"

[[footer]]
name = "research"
url = "research/"

