################### English navigation ####################

# main menu
[[main]]
name = "About"
url = "about/"
weight = 1

[[main]]
name = "Team"
url = "team/"
weight = 2

[[main]]
name = "Publications"
url = "publications/"
weight = 3

[[main]]
weight = 4
name = "Pages"
hasChildren = true


  [[main]]
  parent = "Pages"
  name = "notice"
  url = "notice/"

  [[main]]
  parent = "Pages"
  name = "event"
  url = "event/"

  [[main]]
  parent = "Pages"
  name = "scholarship"
  url = "scholarship/"

  [[main]]
  parent = "Pages"
  name = "research"
  url = "research/"
  
  
[[main]]
name = "Contact"
url = "contact/"
weight = 5


# footer menu

[[footer]]
name = "teacher"
url = "teacher/"

[[footer]]
name = "notice"
url = "notice/"

[[footer]]
name = "event"
url = "event/"

[[footer]]
name = "scholarship"
url = "scholarship/"

[[footer]]
name = "research"
url = "research/"

